# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
mod_version=0.15.0

# Mod Properties
maven_group=work.lclpnet.mods
archives_base_name=pal

# Dependencies
fabric_version=0.126.0+1.21.5
kibu_version=0.145.0+1.21.5
kibu_world_api_version=0.6.3+1.21.5
fantasy_version=0.6.7+1.21.5